sudo: false

language: node_js
node_js:
  - stable

cache:
  directories:
    - node_modules

before_script:
  - wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  - unzip BrowserStackLocal-linux-x64.zip
  - "./BrowserStackLocal $BROWSER_STACK_ACCESS_KEY localhost,8001,0 > /dev/null &"
  - sleep 10

branches:
  only:
    - master
