sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '10'
env:
- TEST_ENV=cjs
- TEST_ENV=umd
- TEST_ENV=source
install:
- npm ci
before_script:
- npm run build
script:
- npm run lint
- npm test
